In [28]:
import numpy as np

In [29]:
#1)	0 ile 9 arasındaki tam sayıları içeren tek boyutlu bir NumPy dizisi (array) oluşturun.
arr1=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
#2 Sadece sıfırlardan oluşan 3X4 boyutlarında bir matris oluşturun.
arr_zero=np.zeros((3,4))
print(arr_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
#3)	•  Sadece birlerden oluşan 2X3 boyutlarında bir matris oluşturun.
arr_one=np.ones((2,3))
print(arr_one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
#4)	np.arange(12).reshape(3, 4) ile oluşturulan bir dizinin boyutunu (shape),
#eleman sayısını (size) ve kaç boyuta sahip olduğunu (ndim) bulun
arr4=np.arange(12).reshape(3,4)
print(arr4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
print("Array shape:",arr4.shape,"\nArray size:",arr4.size,"\nArray boyutu:",arr4.ndim)

Array shape: (3, 4) 
Array size: 12 
Array boyutu: 2


In [34]:
#5)	[10, 20, 30, 40] listesini 64-bit tam sayı (int64) veri tipinde bir NumPy dizisine dönüştürün.
arr5=[10,20,30,40]
yeni_arr=np.array(arr5, dtype=np.int64)
print(yeni_arr)

[10 20 30 40]


In [35]:
#6)	np.arange(20) dizisi içindeki 5'ten büyük ve 15'ten küçük olan tüm elemanları seçerek yeni bir dizi oluşturun.
arr6=np.arange(20)
yeni_arr6=[arr6 for i in arr6 if 5<i<15]
print(arr6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [36]:
#6)	np.arange(20) dizisi içindeki 5'ten büyük ve 15'ten küçük olan tüm elemanları seçerek yeni bir dizi oluşturun.
arr6=np.arange(20)
yeni_arr6 = arr6[(arr6 > 5) & (arr6 < 15)]
print(yeni_arr6)

[ 6  7  8  9 10 11 12 13 14]


In [37]:
#7)	•  a = np.array([1, 2, 3]) ve b = np.array([4, 5, 6]) dizilerini oluşturun.
#8)	•  Bu iki dizinin toplamını ve çarpımını (eleman bazında) hesaplayın.
a=np.array([1,2,3])
b=np.array([4,5,6])
toplam=a+b
çarpma=a*b
print("toplam:",toplam,"\nçarpma:",çarpma)

toplam: [5 7 9] 
çarpma: [ 4 10 18]


In [38]:
#9)	M = np.arange(1, 26).reshape(5, 5) matrisini oluşturun
M=np.arange(1,26).reshape(5,5)
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [39]:
#10)	Matrisin ikinci satırını ([6, 7, 8, 9, 10]) ve üçüncü sütununu ([3, 8, 13, 18, 23]) seçip ekrana yazdırın.
print(M[1])
print(M[:,2])

[ 6  7  8  9 10]
[ 3  8 13 18 23]


In [40]:
#12)	3X2 boyutunda rastgele tam sayılardan oluşan bir matris oluşturun ve bu matrisin transpozunu (devriğini) alın (2 X3 olmalı).arr
arr_12=np.random.randint(1,7,(3,2))
print(arr_12)
print(arr_12.T)

[[3 4]
 [2 2]
 [4 2]]
[[3 2 4]
 [4 2 2]]


In [41]:
#14)	dizi = np.array([1, 2, np.nan, 4, 5, np.nan, 7]) dizisindeki boş (NaN) eleman sayısını bulun.
dizi = np.array([1, 2, np.nan, 4, 5, np.nan, 7])
print(np.isnan(dizi).sum())

2


In [42]:
#15)	5X5 boyutlarında rastgele tam sayılardan oluşan bir matris oluşturun
arr_15=np.random.randint(1,26,(5,5))
print(arr_15)

[[ 3  6  6 21  8]
 [17 13 25  6 20]
 [ 4  9 24 10 13]
 [ 8 18 16  1  1]
 [16  8  1  1 21]]


In [43]:
#16)	Bu matrisin tüm elemanlarının ortalamasını, en büyük değerini ve sütun bazındaki standart sapmasını (axis=0 kullanarak) hesaplayın.
print(arr_15.mean(),"\n",arr_15.max(),"\n",arr_15.min())

11.04 
 25 
 1


In [44]:
#17)	a = np.array([1, 2]) ve b = np.array([3, 4]) dizilerini yatay (hstack) ve dikey (vstack) olarak birleştirin.
a = np.array([1, 2])
b = np.array([3, 4])

print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [45]:
#18)	A = np.array([[1, 2], [3, 4]]) ve B = np.array([[5, 6], [7, 8]]) matrislerini oluşturun.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [46]:
#19)	Bu iki matrisin matris çarpımını (dot product) hesaplayın. (Skaler çarpım değil!)
print(A.dot(B))

[[19 22]
 [43 50]]


In [48]:
#21) Bu matrisin her bir sütununa, o sütunun ortalama değerini çıkararak veriyi merkezleyin (ortalama sıfır olacak şekilde).
arr_21=np.random.randint(1,26,(5,5))
print( arr_21)

a=arr_21.mean(axis=0)
print(a)

arr_21_centered = arr_21 - a
print( arr_21_centered)

print( arr_21_centered.mean(axis=0))

[[13 18 21 25 18]
 [23  7  3  3 20]
 [11 14  9 16 14]
 [22 20 10 20  3]
 [16  4 22  2 20]]
[17.  12.6 13.  13.2 15. ]
[[ -4.    5.4   8.   11.8   3. ]
 [  6.   -5.6 -10.  -10.2   5. ]
 [ -6.    1.4  -4.    2.8  -1. ]
 [  5.    7.4  -3.    6.8 -12. ]
 [ -1.   -8.6   9.  -11.2   5. ]]
[0.00000000e+00 3.55271368e-16 0.00000000e+00 7.10542736e-16
 0.00000000e+00]


In [49]:
#22)	C = np.array([[4, 7], [2, 6]]) matrisini oluşturun.
C = np.array([[4, 7], [2, 6]])

In [50]:
#23)	Matrisin determinantını hesaplayın.
print(np.linalg.det(C))

10.000000000000002


In [53]:
#24)	Matrisin tersini (inverse) hesaplayın ve ters matris ile orijinal matrisi çarparak birim matris (Identity Matrix) elde edip etmediğinizi kontrol edin.
Ters=np.linalg.inv(C)
print(Ters)

print(Ters*C)

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 2.4 -4.9]
 [-0.4  2.4]]


In [58]:
#25)	veri = np.array([1, 2, 1, 4, 5, 2, 7, 1]) dizisindeki benzersiz elemanları ve her bir elemanın kaç kez tekrarlandığını bulun.
veri = np.array([1, 2, 1, 4, 5, 2, 7, 1])
print(np.unique(veri,return_counts=True))


(array([1, 2, 4, 5, 7]), array([3, 2, 1, 1, 1]))


In [59]:
#26)	dizi = np.random.randn(100) (Normal dağılımdan 100 rastgele sayı) dizisini oluşturun.
dizi = np.random.randn(100)

In [60]:
#27)	Dizideki tüm değerleri -2 ve 2 aralığına kırpın (clip). Yani, -2'den küçük olanları -2 yapın, 2'den büyük olanları 2 yapın.
clipped_dizi = np.clip(dizi, -2, 2)

print( dizi[:10])
print( clipped_dizi[:10])

[-0.79893558  0.06545716  0.01536488  0.60675057 -0.1471765   0.12223953
 -1.54836236 -0.88967792  1.42778926  0.77528604]
[-0.79893558  0.06545716  0.01536488  0.60675057 -0.1471765   0.12223953
 -1.54836236 -0.88967792  1.42778926  0.77528604]


In [61]:
#28)	v1 = np.array([1, 2, 3]) ve v2 = np.array([4, 5, 6]) vektörlerini oluşturun.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [62]:
#29)	Bu iki vektörün nokta ürününü (inner product) ve dış ürününü (outer product) hesaplayın.

inner_product = np.dot(v1, v2)
print("Inner Product (Nokta Ürünü):", inner_product)

outer_product = np.outer(v1, v2)
print("\nOuter Product (Dış Ürünü):\n", outer_product)

Inner Product (Nokta Ürünü): 32

Outer Product (Dış Ürünü):
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
#30)	1.000.000 elemanlı büyük bir listeyi (py_list) ve aynı elemanları içeren bir NumPy dizisini (np_array) oluşturun


In [64]:
#30) 1.000.000 elemanlı büyük bir listeyi (py_list) ve aynı elemanları içeren bir NumPy dizisini (np_array) oluşturun

import time

start_time = time.time()
py_list = list(range(1000000))
end_time = time.time()
print(f"Python list created in {end_time - start_time:.4f} seconds.")

start_time = time.time()
np_array = np.arange(1000000)
end_time = time.time()
print(f"NumPy array created in {end_time - start_time:.4f} seconds.")

# Display the first few elements and the size to confirm
print("\nFirst 5 elements of py_list:", py_list[:5])
print("Size of py_list:", len(py_list))
print("\nFirst 5 elements of np_array:", np_array[:5])
print("Size of np_array:", np_array.size)

Python list created in 0.0496 seconds.
NumPy array created in 0.0200 seconds.

First 5 elements of py_list: [0, 1, 2, 3, 4]
Size of py_list: 1000000

First 5 elements of np_array: [0 1 2 3 4]
Size of np_array: 1000000
